server:
  port: 8080


spring:
  jackson:
    parser:
      allow-single-quotes: true

  application:
    name: webcheck-server

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/webcheck
    username: root
    password: 12345678
    driverClassName: com.mysql.cj.jdbc.Driver